### ISSUE TITLE
[bug] one of the cores it pinned at 100% while the app is running.

### ISSUE THREAD

**Issue by eskoONE** [Pyntux/TimerDown#1]
not sure whats happening here, but one of the cpus is always pinned at 100%. doesnt matter if in tray or or is running or not.  

im on arch linux, latest kernel and bspwm. 

ill have a look tomorrow and see if i can figure out what is happening.

**Comment by Pyntux** [comment]
Yes, there is a problem.... I really do not know why is this.... A week ago everything was OK... maybe some updated package changed something... I will try to resolve that, but I am not a expert in python, so any kind of help will be good.

EDIT:

OK, there is problem with "Qtimer", look app and system monitor without clock... I will try to resolve that...
![TimerDown_without_clock](https://user-images.githubusercontent.com/2485335/119298999-6d33ef80-bc5e-11eb-9c29-093f11671e22.png)

**Comment by eskoONE** [comment]
from what i read in the documentation, qtimer updates every millisecond. that ~~would~~ could cause she issue we have here. and since python is single threaded, as far as i know anyway, it only pins one cpu to 100%. 

there are two alternatives to qtimer, startTimer() and QBasicTimer(). have a look at that [here](https://doc.qt.io/qtforpython/PySide6/QtCore/QTimer.html#more).

**Comment by Pyntux** [comment]
I will look into it and try to change code... Thank you!

**Comment by Pyntux** [comment]
I think problem is solved now... This is quick solution.... I will try to change whole code this days... Could you try -git version?

**Comment by eskoONE** [comment]
seems to be solved for me as well, ty. 

there are a few things id like to ask for implementation if you dont mind. its usually nice to save the last inserted time value in the field instead of resetting it to 15 every time. 

another nice to have feature would be to have the option to send the application to the tray on closing the app instead of having the button to minimize to tray. thats how it is usually done and it makes things more convenient for ppl using a window manager.

these are things i could implement myself if u dont like to add it to your project. so no worries.

have a good day.

**Comment by Pyntux** [comment]
Thats nice ideas... Saving last entered time is easy to implement (just to
change one line), but I do need to look for tray option when click close
button... I will make another branch so we can make those changes and
implement them in to app if you have time to help? :)

**Comment by eskoONE** [comment]
> I will make another branch so we can make those changes and implement them in to app if you have time to help? :)

i would like to, but i dont have much time atm. i will look into it once i do though. see if you can solve this on your own ;) good luck :)
